Remove deprecated transaction use
committing manually has changed in Django 1.8 (https://docs.djangoproject.com/en/1.8/topics/db/transactions/). Resolve the issue "AttributeError: 'module' object has no attribute 'commit_manually'" on line 41 of import_tweets.